server:
  port: 8084

spring:
  application:
    name: eureka

  cloud:
    config:
      uri: http://localhost:8082
      profile: dev

eureka:
      client:
        registerWithEureka: false
        fetchRegistry: false

logging:
  level:
    org.springframework.cloud: 'DEBUG'
